# Generated by Django 5.2.7 on 2025-10-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
